name: github-integration
description: A Helm chart for github-integration service
version: 0.6.4
home: https://k8s.community/
sources:
  - https://github.com/k8s-community/github-integration
maintainers:
  - name: Kubernetes Community Authors
    email: k8s.community@gmail.com
engine: gotpl
